### ISSUE TITLE
TCG Player UI Update seems to have broken the extension

### ISSUE THREAD

**Issue by natefinch** [ahallaha/tcgplayer-shopping-assistant#9]
I'm not seeing stores getting highlighted or states getting added. I don't have a lot of experience with Javascript, but looking at the html and the code, looks like maybe the code assumes item listings have both `listing-item` and `product-details__listings-results` as classes, but now only the wrapper div has `product-details__listings-results` as a class, and the individual items just have `listing-item`.

If I add `product-details__listings-results` to one of the item sections, they get a state again.

So I think if productObserver changes to only look for `listing-item` it'll work again.

**Comment by ahallaha** [comment]
Thanks for opening this and doing so much analysis for me. Sorry for the late response. I updated that selector and it fixes the location and adds the checkmark but doesn't highlight the row. I'm going to look into that and then I'll push asap.

**Comment by ahallaha** [comment]
I think something is broken within chrome-extension-upload-action because I'm getting an error from the action but I was able to publish manually. Hopefully it will be accepted and deployed soon.
